#!/bin/zsh

# Default programs:
export EDITOR="nvim"
export TERMINAL="kitty"
export BROWSER="vivaldi"

export PATH="$PATH:${$(find ~/.local/bin -type d -printf %p:)%%:}"

# XDG Paths
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
