#!/usr/bin/env bash
# shellcheck disable=SC2034
# This issue is ignored because it is part of a larger file that calls upon all variables listed

# To edit this file copy it to `${HOME}/.config/dmscripts/config`
# `cp /etc/dmscripts/config ${HOME}/.config/dmscripts/config`

# Defined variables, modify anything in quotes to your prefered software

# -p is needed as we use prompts, alternative programs have to handle prompts well.

DMENU="wofi --show dmenu -i -p"

# DMBROWSER="brave"
DMBROWSER="vivaldi"
# DMBROWSER="qutebrowser"

DMTERM="kitty -e"
# DMTERM="alacritty -e"

DMEDITOR="${DMTERM} nvim"


# This case statement lets you change what the DMENU variable is for different scripts, so if you
# want a unique variable for each script you can
# syntax is as follows:
# "<ending-of-script>") DMENU="your variable here"
# *) should be left blank, global variables are defined above

# include -p in standard dmenu as we use prompts by default
case "${0##*-}" in
#  "colpick") DMENU="dmenu -i -p";;
#  "confedit") DMENU="dmenu -i -l 30 -p";;
#  "youtube") DMBROWSER="firefox";;
  *);;
esac

# "${0##*-}" means grab the 0th argument (which is always the path to the program) starting from the
# last dash. This gives us the word after the - which is what we are searching for in the case
# statement. ie dm-man -> man

# An awk equivalent is: 
# awk -F"-" '{print $NF}'
# Sadly cut has no easy equivalent

# dm-bookman 
bookman_show_source=1

# dm-confedit
declare -A confedit_list
confedit_list[confedit]="$HOME/.config/dmscripts/config"
confedit_list[sway]="$HOME/.config/sway/config"
confedit_list[hypr]="$HOME/.config/hypr/hyprland.conf"
confedit_list[waybar]="$HOME/.config/waybar/config.jsonc"
confedit_list[arch]="$HOME/.local/share/setup/arch/3-packages.sh"
confedit_list[nixos]="$HOME/.local/share/setup/nixos/configuration.nix"
confedit_list[nvim]="$HOME/.config/nvim/init.lua"
confedit_list[kitty]="$HOME/.config/kitty/kitty.conf"
confedit_list[lf]="$HOME/.config/lf/lfrc"
confedit_list[wofi]="$HOME/.config/wofi/config"
confedit_list[zsh]="$HOME/.zshrc"
# confedit_list[zprofile]="$HOME/.zprofile"

